# Generated by Django 5.1.4 on 2024-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pas',
            field=models.BooleanField(default=False),
        ),
    ]
